name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
    - name: printenv
      run: echo $PATH
      
  build:

    runs-on: ubuntu-latest

    env: 
    steps:
    - uses: actions/checkout@v3

    - name: make
      run: make all
